# Welcome to Serverless!


service: inventory-management-system
app: inventory-management-system

provider:
  name: aws
  stage: prod
  region: ${env:REGION}
  #TODO remove iamRoleStatements if you are not using SQS
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "es:ESHttpGet"
        - "es:ESHttpPut"
        - "es:ESHttpDelete"
        - "es:ESHttpPost"
      Resource: "arn:aws:es:${self:provider.region}:${env:AWS_ACCOUNT_ID}:*"
  runtime: nodejs10.x


functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'


resources:
  Resources:

plugins:
  - serverless-offline
  - serverless-dotenv-plugin